#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#配置服务端口号      
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          #远程获取git配置信息
          uri: https://github.com/wangxuegang/springcloud.git
  application:
    #服务名称
    name: config-server