## eureka注册中心服务器端口号
server.port = 8761

## eureka注册中心服务器IP地址
eureka.instance.hostname = localhost

## 是否注册自身到eureka注册中心服务器中
eureka.client.registerWithEureka = true

## 是否从eureka注册中心服务器获取注册信息
eureka.client.fetchRegistry = false

## 设置eureka注册中心服务器所在的地址
eureka.client.serviceUrl.defaultZone = http://${eureka.instance.hostname}:${server.port}/eureka/
